Arbitrary station positions (drag+drop and refactor)
otakulan/lanparty-seating pull request #93
Opened 2024-08-18 04:19 UTC by babbaj

- Simplified the DB schema (made station_id the primary key for stations and stations_status)
- Squashed all the migrations because we can just reset the DB
- Removed `columns` and `rows` from settings, now computed from xy data
- Station positions are defined by the station_layout table
- Improved settings page (drag+drop, number of stations, empty slots)
- Spammed commits to pad my github activity

2024-09-14 23:32 UTC, starcraft66 commented on lib/lanpartyseating_web/live/settings_live.ex
> +        IO.inspect(failed_value)
Use `Logger.debug/1` here instead of directly printing out with `IO`.

2024-09-14 23:44 UTC, starcraft66 requested changes

2024-09-14 23:44 UTC, starcraft66 commented on lib/lanpartyseating_web/live/settings_live.ex
> +        IO.inspect(failed_value)
Use `Logger.debug/1` here instead of directly printing out with `IO`.

2024-09-14 23:44 UTC, starcraft66 commented on lib/lanpartyseating_web/live/settings_live.ex
> +
Please make empty colums/rows disappear from the visual designer when hitting save to reflect the state of the database and other display pages at that moment.

2024-09-14 23:44 UTC, starcraft66 commented on lib/lanpartyseating/logic/settings_logic.ex
> +  # returns an Ecto.Multi that has to be written
Wrap this in an `@doc """ """` string so it can be rendered out into generated documentation

2024-09-14 23:44 UTC, starcraft66 commented on lib/lanpartyseating_web/live/settings_live.ex
> +  # {columns, rows}
Wrap this in an `@doc """ """` string so it can be rendered out into generated documentation

2024-09-14 23:44 UTC, starcraft66 commented on lib/lanpartyseating/logic/station_logic.ex
> +  def save_stations(grid) do
Rename this function to something more clear because it does not actually save the stations as it is written now.

2025-06-15 06:50 UTC, babbaj commented on lib/lanpartyseating_web/components/layouts/live.html.heex
> +          <div style="white-space: pre-wrap;"><%= Phoenix.Flash.get(@flash, :info) %></div>
this was necessary to get newlines to work. it looks exactly the same otherwise.

2025-06-15 06:56 UTC, babbaj commented on lib/lanpartyseating_web/live/settings_live.ex
> +      e ->
without this the process is killed with no visual indication which is probably the case everywhere else db transactions are done. I think some sort of global exception handler should be added to take care of that.

2025-06-19 03:02 UTC, starcraft66 commented on lib/lanpartyseating_web/live/settings_live.ex
> +      e ->
Yeah this project has never had a great error handling story in that respect. We can worry about it in another PR and focus on features for this year.

2025-06-19 03:27 UTC, starcraft66 commented on priv/repo/migrations/20240814023743_squash_migrations.exs
> +      add(:station_id, :integer, primary_key: true)
We've discussed in dms that this won't be required to prevent data loss in case of accidental resizing mishaps

2025-06-19 03:38 UTC, merged